### ISSUE TITLE
article pandoc and tex problem

### ISSUE THREAD

**Issue by sepahead** [ReScience/ReScience-submission#31]
Greetings,

I tried to use the provided template after installing the latest TeX Live, pandoc, pandoc-crossref but I get these errors:

```
allStack (from HasCallStack):
  error, called at ./Text/Pandoc/JSON.hs:113:48 in pandoc-types-1.17.0.5-8QF4dYNSmQFGMk7bUzM7GZ:Text.Pandoc.JSON
pandoc: Error running filter /home/sepehr/.cabal/bin/pandoc-crossref
Filter returned error status 1
Makefile:10: recipe for target 'rescience-template.tex' failed
make: *** [rescience-template.tex] Error 83
```

I tried without a sandbox, but I get the same error. I tried installing pandoc-crossref 0.1.5.6 but cabal gets stuck forever.

**Comment by rougier** [comment]
What is the exact command you're using with pandoc ?

You can try to debug by creating a fake file with (only) all your references and try to compile. If this doesn' t work, you can try to comment out all your references and add them one by one to check if a given reference is responsible.

**Comment by sepahead** [comment]
Thanks! Problem solved. pandoc-crossref was using a wrong pandoc version.
