### ISSUE TITLE
Problem with pandoc-crossref

### ISSUE THREAD

**Issue by rLarisch** [ReScience/ReScience-submission#44]
Dear ReScience Team,

since two weeks, I try to install pandoc-crossref on my linux-mint system. Sadly, the interplay of cabal and the ghc brings always a lot of errors. Because of this, I want to ask, if it possible to create the *.pdf without pandoc and pandoc-crossref ? Is it maybe possible, that I just recreate the *.tex file for my own, without pandoc?

Many thanks in advance!

**Comment by pdebuyl** [comment]
Hi @rLarisch I use Debian and could setup the build system. Would you like some assistance?

Ultimately, we require all articles to be submitted in markdown following our template so direct editing of LaTeX files is not an option.

**Comment by rLarisch** [comment]
I start a vm with ArchLinux and now pandoc-crossref works.^^
So issue can be closed.

Thanks anyway

**Comment by pdebuyl** [comment]
ok, thanks for the update

**Comment by ThomasA** [comment]
Just a thought: could we perhaps offer a Docker image or something like that where the article build environment Just Works™ ?

**Comment by rougier** [comment]
Any volunteer for @ThomasA proposal ?
