### ISSUE TITLE
Change the name of the pdf

### ISSUE THREAD

**Issue by antoine-lizee** [ReScience/ReScience-submission#5]
In the first published article, the name of the pdf has not been changed, which makes the downloaded file have a less than optimal name ("article"). I'm wondering if changing the name to "your_article_name.md" would be suggestive enough for the user of the submission repo to actually change the name of the file!

**Comment by antoine-lizee** [comment]
The proposed PR changes the name of the files to something more obviously changeable. The solution could be totally different though, like enforcing to change the file name during the review process, or even better, a baked-in change of the downloadable file name when linking from the website to the pdf of the repo (I have no idea how to do that though).

**Comment by rougier** [comment]
Thanks. PR merged.
