### ISSUE TITLE
pandoc command revision?

### ISSUE THREAD

**Issue by opetchey** [ReScience/ReScience-submission#7]
Probably need to change:
--bibliography=article.bib
to
--bibliography=your_article_name.bib

(And thanks for the journal, it looks very interesting; I hope to soon make a submission.)

**Comment by rougier** [comment]
Thanks, you're right but I cannot find the line. In the README you mean ?

**Comment by opetchey** [comment]
sorry, yes, here
https://github.com/ReScience/ReScience-submission/blob/master/article/README.md

**Comment by antoine-lizee** [comment]
Wow, that was quick. I just posted a PR on my own, but good catch.

**Comment by rougier** [comment]
Thanks. It has been fixed.
